/** QS-style university records used by the Syncfusion PivotView overview demo. */
export interface UniversityRecord {
  [key: string]: string | number;
  rank_display: number;
  university: string;
  country: string;
  city: string;
  region: string;
  type: string;
  international_students: number;
  faculty_count: number;
  research_output: string;
  student_faculty_ratio: number;
  link: string;
  logo: string;
}

const LOGO = '/assets/images/grid/user-male.svg';

export const Universitydata: UniversityRecord[] = [
  { rank_display: 1, university: 'Massachusetts Institute of Technology', country: 'United States', city: 'Cambridge', region: 'North America', type: 'Private', international_students: 3840, faculty_count: 1300, research_output: 'Very High', student_faculty_ratio: 3, link: 'https://www.topuniversities.com/universities/massachusetts-institute-technology-mit', logo: LOGO },
  { rank_display: 2, university: 'University of Cambridge', country: 'United Kingdom', city: 'Cambridge', region: 'Europe', type: 'Public', international_students: 4200, faculty_count: 1100, research_output: 'Very High', student_faculty_ratio: 11, link: 'https://www.topuniversities.com/universities/university-cambridge', logo: LOGO },
  { rank_display: 3, university: 'University of Oxford', country: 'United Kingdom', city: 'Oxford', region: 'Europe', type: 'Public', international_students: 4500, faculty_count: 1200, research_output: 'Very High', student_faculty_ratio: 11, link: 'https://www.topuniversities.com/universities/university-oxford', logo: LOGO },
  { rank_display: 4, university: 'Harvard University', country: 'United States', city: 'Cambridge', region: 'North America', type: 'Private', international_students: 5200, faculty_count: 2400, research_output: 'Very High', student_faculty_ratio: 7, link: 'https://www.topuniversities.com/universities/harvard-university', logo: LOGO },
  { rank_display: 5, university: 'Stanford University', country: 'United States', city: 'Stanford', region: 'North America', type: 'Private', international_students: 3800, faculty_count: 2100, research_output: 'Very High', student_faculty_ratio: 5, link: 'https://www.topuniversities.com/universities/stanford-university', logo: LOGO },
  { rank_display: 6, university: 'Imperial College London', country: 'United Kingdom', city: 'London', region: 'Europe', type: 'Public', international_students: 6100, faculty_count: 900, research_output: 'Very High', student_faculty_ratio: 11, link: 'https://www.topuniversities.com/universities/imperial-college-london', logo: LOGO },
  { rank_display: 7, university: 'ETH Zurich', country: 'Switzerland', city: 'Zurich', region: 'Europe', type: 'Public', international_students: 2900, faculty_count: 600, research_output: 'Very High', student_faculty_ratio: 8, link: 'https://www.topuniversities.com/universities/eth-zurich-swiss-federal-institute-technology', logo: LOGO },
  { rank_display: 8, university: 'National University of Singapore', country: 'Singapore', city: 'Singapore', region: 'Asia', type: 'Public', international_students: 8700, faculty_count: 1800, research_output: 'Very High', student_faculty_ratio: 12, link: 'https://www.topuniversities.com/universities/national-university-singapore-nus', logo: LOGO },
  { rank_display: 9, university: 'University College London', country: 'United Kingdom', city: 'London', region: 'Europe', type: 'Public', international_students: 12000, faculty_count: 1400, research_output: 'Very High', student_faculty_ratio: 10, link: 'https://www.topuniversities.com/universities/university-college-london', logo: LOGO },
  { rank_display: 10, university: 'University of California, Berkeley', country: 'United States', city: 'Berkeley', region: 'North America', type: 'Public', international_students: 6800, faculty_count: 1600, research_output: 'Very High', student_faculty_ratio: 20, link: 'https://www.topuniversities.com/universities/university-california-berkeley-ucb', logo: LOGO },
  { rank_display: 11, university: 'University of Chicago', country: 'United States', city: 'Chicago', region: 'North America', type: 'Private', international_students: 3200, faculty_count: 1100, research_output: 'Very High', student_faculty_ratio: 6, link: 'https://www.topuniversities.com/universities/university-chicago', logo: LOGO },
  { rank_display: 12, university: 'University of Pennsylvania', country: 'United States', city: 'Philadelphia', region: 'North America', type: 'Private', international_students: 4100, faculty_count: 1500, research_output: 'Very High', student_faculty_ratio: 6, link: 'https://www.topuniversities.com/universities/university-pennsylvania', logo: LOGO },
  { rank_display: 13, university: 'Cornell University', country: 'United States', city: 'Ithaca', region: 'North America', type: 'Private', international_students: 5600, faculty_count: 1700, research_output: 'Very High', student_faculty_ratio: 9, link: 'https://www.topuniversities.com/universities/cornell-university', logo: LOGO },
  { rank_display: 14, university: 'University of Melbourne', country: 'Australia', city: 'Melbourne', region: 'Oceania', type: 'Public', international_students: 14000, faculty_count: 2200, research_output: 'Very High', student_faculty_ratio: 15, link: 'https://www.topuniversities.com/universities/university-melbourne', logo: LOGO },
  { rank_display: 15, university: 'California Institute of Technology', country: 'United States', city: 'Pasadena', region: 'North America', type: 'Private', international_students: 650, faculty_count: 350, research_output: 'Very High', student_faculty_ratio: 3, link: 'https://www.topuniversities.com/universities/california-institute-technology-caltech', logo: LOGO },
  { rank_display: 16, university: 'Yale University', country: 'United States', city: 'New Haven', region: 'North America', type: 'Private', international_students: 2800, faculty_count: 1200, research_output: 'Very High', student_faculty_ratio: 6, link: 'https://www.topuniversities.com/universities/yale-university', logo: LOGO },
  { rank_display: 17, university: 'Peking University', country: 'China', city: 'Beijing', region: 'Asia', type: 'Public', international_students: 4200, faculty_count: 4500, research_output: 'Very High', student_faculty_ratio: 6, link: 'https://www.topuniversities.com/universities/peking-university', logo: LOGO },
  { rank_display: 18, university: 'Princeton University', country: 'United States', city: 'Princeton', region: 'North America', type: 'Private', international_students: 1900, faculty_count: 900, research_output: 'Very High', student_faculty_ratio: 5, link: 'https://www.topuniversities.com/universities/princeton-university', logo: LOGO },
  { rank_display: 19, university: 'University of New South Wales', country: 'Australia', city: 'Sydney', region: 'Oceania', type: 'Public', international_students: 16000, faculty_count: 2100, research_output: 'Very High', student_faculty_ratio: 16, link: 'https://www.topuniversities.com/universities/university-new-south-wales-unsw-sydney', logo: LOGO },
  { rank_display: 20, university: 'University of Sydney', country: 'Australia', city: 'Sydney', region: 'Oceania', type: 'Public', international_students: 15000, faculty_count: 2000, research_output: 'Very High', student_faculty_ratio: 15, link: 'https://www.topuniversities.com/universities/university-sydney', logo: LOGO },
  { rank_display: 21, university: 'University of Toronto', country: 'Canada', city: 'Toronto', region: 'North America', type: 'Public', international_students: 18000, faculty_count: 3200, research_output: 'Very High', student_faculty_ratio: 19, link: 'https://www.topuniversities.com/universities/university-toronto', logo: LOGO },
  { rank_display: 22, university: 'University of Edinburgh', country: 'United Kingdom', city: 'Edinburgh', region: 'Europe', type: 'Public', international_students: 9000, faculty_count: 1300, research_output: 'Very High', student_faculty_ratio: 12, link: 'https://www.topuniversities.com/universities/university-edinburgh', logo: LOGO },
  { rank_display: 23, university: 'Columbia University', country: 'United States', city: 'New York', region: 'North America', type: 'Private', international_students: 11000, faculty_count: 1800, research_output: 'Very High', student_faculty_ratio: 6, link: 'https://www.topuniversities.com/universities/columbia-university', logo: LOGO },
  { rank_display: 24, university: 'Université PSL', country: 'France', city: 'Paris', region: 'Europe', type: 'Public', international_students: 5200, faculty_count: 1100, research_output: 'Very High', student_faculty_ratio: 10, link: 'https://www.topuniversities.com/universities/universite-psl', logo: LOGO },
  { rank_display: 25, university: 'Tsinghua University', country: 'China', city: 'Beijing', region: 'Asia', type: 'Public', international_students: 3800, faculty_count: 4800, research_output: 'Very High', student_faculty_ratio: 12, link: 'https://www.topuniversities.com/universities/tsinghua-university', logo: LOGO },
  { rank_display: 26, university: 'Nanyang Technological University', country: 'Singapore', city: 'Singapore', region: 'Asia', type: 'Public', international_students: 7500, faculty_count: 1500, research_output: 'Very High', student_faculty_ratio: 14, link: 'https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu', logo: LOGO },
  { rank_display: 27, university: 'University of Hong Kong', country: 'Hong Kong SAR', city: 'Hong Kong', region: 'Asia', type: 'Public', international_students: 8200, faculty_count: 1200, research_output: 'Very High', student_faculty_ratio: 17, link: 'https://www.topuniversities.com/universities/university-hong-kong', logo: LOGO },
  { rank_display: 28, university: 'University of Tokyo', country: 'Japan', city: 'Tokyo', region: 'Asia', type: 'Public', international_students: 4200, faculty_count: 2800, research_output: 'Very High', student_faculty_ratio: 10, link: 'https://www.topuniversities.com/universities/university-tokyo', logo: LOGO },
  { rank_display: 29, university: 'University of Manchester', country: 'United Kingdom', city: 'Manchester', region: 'Europe', type: 'Public', international_students: 11000, faculty_count: 1600, research_output: 'Very High', student_faculty_ratio: 14, link: 'https://www.topuniversities.com/universities/university-manchester', logo: LOGO },
  { rank_display: 30, university: 'Seoul National University', country: 'South Korea', city: 'Seoul', region: 'Asia', type: 'Public', international_students: 2800, faculty_count: 2200, research_output: 'Very High', student_faculty_ratio: 11, link: 'https://www.topuniversities.com/universities/seoul-national-university', logo: LOGO },
  { rank_display: 101, university: 'University of Auckland', country: 'New Zealand', city: 'Auckland', region: 'Oceania', type: 'Public', international_students: 8500, faculty_count: 1400, research_output: 'High', student_faculty_ratio: 17, link: 'https://www.topuniversities.com/universities/university-auckland', logo: LOGO },
  { rank_display: 105, university: 'Technical University of Munich', country: 'Germany', city: 'Munich', region: 'Europe', type: 'Public', international_students: 6200, faculty_count: 1100, research_output: 'Very High', student_faculty_ratio: 15, link: 'https://www.topuniversities.com/universities/technical-university-munich', logo: LOGO },
  { rank_display: 110, university: 'University of British Columbia', country: 'Canada', city: 'Vancouver', region: 'North America', type: 'Public', international_students: 13000, faculty_count: 2800, research_output: 'Very High', student_faculty_ratio: 18, link: 'https://www.topuniversities.com/universities/university-british-columbia', logo: LOGO },
  { rank_display: 115, university: 'McGill University', country: 'Canada', city: 'Montreal', region: 'North America', type: 'Public', international_students: 9500, faculty_count: 1700, research_output: 'Very High', student_faculty_ratio: 16, link: 'https://www.topuniversities.com/universities/mcgill-university', logo: LOGO },
  { rank_display: 120, university: 'KU Leuven', country: 'Belgium', city: 'Leuven', region: 'Europe', type: 'Public', international_students: 7800, faculty_count: 1200, research_output: 'High', student_faculty_ratio: 20, link: 'https://www.topuniversities.com/universities/ku-leuven', logo: LOGO },
  { rank_display: 125, university: 'University of Amsterdam', country: 'Netherlands', city: 'Amsterdam', region: 'Europe', type: 'Public', international_students: 6200, faculty_count: 900, research_output: 'High', student_faculty_ratio: 14, link: 'https://www.topuniversities.com/universities/university-amsterdam', logo: LOGO },
  { rank_display: 130, university: 'Ludwig-Maximilians-Universität München', country: 'Germany', city: 'Munich', region: 'Europe', type: 'Public', international_students: 5400, faculty_count: 1500, research_output: 'Very High', student_faculty_ratio: 16, link: 'https://www.topuniversities.com/universities/ludwig-maximilians-universitat-munchen', logo: LOGO },
  { rank_display: 135, university: 'University of Copenhagen', country: 'Denmark', city: 'Copenhagen', region: 'Europe', type: 'Public', international_students: 4800, faculty_count: 800, research_output: 'High', student_faculty_ratio: 12, link: 'https://www.topuniversities.com/universities/university-copenhagen', logo: LOGO },
  { rank_display: 140, university: 'Monash University', country: 'Australia', city: 'Melbourne', region: 'Oceania', type: 'Public', international_students: 22000, faculty_count: 3500, research_output: 'Very High', student_faculty_ratio: 18, link: 'https://www.topuniversities.com/universities/monash-university', logo: LOGO },
  { rank_display: 145, university: 'University of Queensland', country: 'Australia', city: 'Brisbane', region: 'Oceania', type: 'Public', international_students: 12000, faculty_count: 1900, research_output: 'Very High', student_faculty_ratio: 17, link: 'https://www.topuniversities.com/universities/university-queensland', logo: LOGO },
  { rank_display: 150, university: 'Kyoto University', country: 'Japan', city: 'Kyoto', region: 'Asia', type: 'Public', international_students: 2100, faculty_count: 2400, research_output: 'Very High', student_faculty_ratio: 9, link: 'https://www.topuniversities.com/universities/kyoto-university', logo: LOGO },
  { rank_display: 155, university: 'Fudan University', country: 'China', city: 'Shanghai', region: 'Asia', type: 'Public', international_students: 3500, faculty_count: 3200, research_output: 'High', student_faculty_ratio: 13, link: 'https://www.topuniversities.com/universities/fudan-university', logo: LOGO },
  { rank_display: 160, university: 'Shanghai Jiao Tong University', country: 'China', city: 'Shanghai', region: 'Asia', type: 'Public', international_students: 4200, faculty_count: 3600, research_output: 'High', student_faculty_ratio: 14, link: 'https://www.topuniversities.com/universities/shanghai-jiao-tong-university', logo: LOGO },
  { rank_display: 165, university: 'University of Michigan', country: 'United States', city: 'Ann Arbor', region: 'North America', type: 'Public', international_students: 7200, faculty_count: 3200, research_output: 'Very High', student_faculty_ratio: 11, link: 'https://www.topuniversities.com/universities/university-michigan-ann-arbor', logo: LOGO },
  { rank_display: 170, university: 'University of California, Los Angeles', country: 'United States', city: 'Los Angeles', region: 'North America', type: 'Public', international_students: 6800, faculty_count: 2900, research_output: 'Very High', student_faculty_ratio: 18, link: 'https://www.topuniversities.com/universities/university-california-los-angeles-ucla', logo: LOGO },
  { rank_display: 175, university: 'Georgia Institute of Technology', country: 'United States', city: 'Atlanta', region: 'North America', type: 'Public', international_students: 5200, faculty_count: 1400, research_output: 'Very High', student_faculty_ratio: 19, link: 'https://www.topuniversities.com/universities/georgia-institute-technology', logo: LOGO },
  { rank_display: 180, university: 'University of Illinois Urbana-Champaign', country: 'United States', city: 'Champaign', region: 'North America', type: 'Public', international_students: 11000, faculty_count: 2600, research_output: 'Very High', student_faculty_ratio: 20, link: 'https://www.topuniversities.com/universities/university-illinois-urbana-champaign', logo: LOGO },
  { rank_display: 185, university: 'Carnegie Mellon University', country: 'United States', city: 'Pittsburgh', region: 'North America', type: 'Private', international_students: 4800, faculty_count: 900, research_output: 'Very High', student_faculty_ratio: 10, link: 'https://www.topuniversities.com/universities/carnegie-mellon-university', logo: LOGO },
  { rank_display: 190, university: 'University of Washington', country: 'United States', city: 'Seattle', region: 'North America', type: 'Public', international_students: 6200, faculty_count: 3100, research_output: 'Very High', student_faculty_ratio: 19, link: 'https://www.topuniversities.com/universities/university-washington', logo: LOGO },
  { rank_display: 195, university: 'University of Texas at Austin', country: 'United States', city: 'Austin', region: 'North America', type: 'Public', international_students: 5800, faculty_count: 2400, research_output: 'Very High', student_faculty_ratio: 18, link: 'https://www.topuniversities.com/universities/university-texas-austin', logo: LOGO },
  { rank_display: 200, university: 'University of Wisconsin-Madison', country: 'United States', city: 'Madison', region: 'North America', type: 'Public', international_students: 4500, faculty_count: 2200, research_output: 'Very High', student_faculty_ratio: 17, link: 'https://www.topuniversities.com/universities/university-wisconsin-madison', logo: LOGO },
];
